import { Skill } from "./types";

export const skills: Skill[] = [
  { name: "Typescript" },
  { name: "Javascript" },
  { name: "React" },
  { name: "NodeJS" },
  { name: "Express" },
  { name: "Docker" },
  { name: "C#" },
  { name: "ASP.NET" },
  { name: "Elasticsearch" },
  { name: "Vite" },
  { name: "Vitest" },
  { name: "Lerna" },
  { name: "Storybook" },
  { name: "Jest" },
  { name: "AWS" },
  { name: "Azure" },
  { name: "Supabase" },
  { name: "Kubernetes" },
  { name: "MySQL" },
  { name: "PostgreSQL" },
  { name: "Python" },
  { name: "Clojure" },
  { name: "Keycloak" },
  { name: "Bootstrap" },
  { name: "Mantine" },
  { name: "HTML" },
  { name: "Sass" },
  { name: "JIRA" },
  { name: "Jenkins" },
  { name: "Azure DevOps" },
  { name: "GitHub" },
  { name: "Gerrit" }
];
