export type Skill = {
  name: string;
};

export const skills: Skill[] = [
  { name: "Typescript" },
  { name: "Javascript" },
  { name: "React" },
  { name: "Tailwind" },
  { name: "Vite" },
  { name: "Vitest" },
  { name: "Testing Library" },
  { name: "MSW" },
  { name: "Storybook" },
  { name: "NodeJS" },
  { name: "Express" },
  { name: "oRPC" },
  { name: "Docker" },
  { name: "C#" },
  { name: "ASP.NET" },
  { name: "Elasticsearch" },
  { name: "GraphQL" },
  { name: "Nx" },
  { name: "Lerna" },
  { name: "Percy" },
  { name: "Happo" },
  { name: "Jest" },
  { name: "AWS" },
  { name: "Azure" },
  { name: "Supabase" },
  { name: "Better Auth" },
  { name: "Kubernetes" },
  { name: "Drizzle" },
  { name: "MySQL" },
  { name: "PostgreSQL" },
  { name: "Radix UI" },
  { name: "Bootstrap" },
  { name: "Mantine" },
  { name: "Elixir" },
  { name: "Phoenix LiveView" },
  { name: "Python" },
  { name: "Clojure" },
  { name: "Keycloak" },
  { name: "HTML" },
  { name: "Sass" },
  { name: "JIRA" },
  { name: "Jenkins" },
  { name: "GitHub" },
  { name: "Azure DevOps" },
];
